AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample Node.js AWS Lambda application
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: #{CodeUri}
      Handler: app.handler
      Runtime: nodejs8.10
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: get